### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by jenokizm** [AdminAnticaptcha/anticaptcha-csharp#1]
Блин ребят вам взападло на нугете собранную либу опубликовать? еще не хватало мне тащить целый проект в решение...

**Comment by ivanovevgeny** [comment]
Согласен, могли же нормально сделать, делов на день вместе с написанием этого API.
То что здесь в гите - тоже какая-то лажа, я в жизни не видел хуже API. Это даже не библиотека, это консольное приложение.
